FROM mcr.microsoft.com/dotnet/sdk:10.0-nanoserver-ltsc2025 AS build
WORKDIR /src

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:10.0-nanoserver-ltsc2025
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Exercise7_1.dll"]
